using ArgParse
using TriMRS

function rda_diff(in1file, in2file, outfile; anonymize=true)
    in1header,in1data = load_rda(in1file)
    in2header,in2data = load_rda(in2file)
    outheader = copy(in1header)
    if anonymize
        outheader["PatientName"] = "xxxxxxxxx"
        outheader["PatientID"] = "xxx"
        outheader["PatientBirthDate"] = "20000101"
    end
    save_rda(outfile, outheader, in1data .- in2data)
end

function megapress_argparse(arg_strings; extra_settings...)
    settings = ArgParseSettings(;extra_settings...)
    @add_arg_table settings begin
        "--output", "-o"
            help = "Output file name.  Default is autogenerated based on the input file names."
        "input_files"
            required=true
            nargs='+'
            help = "One or more input .rda files"
    end
    parse_args(arg_strings, settings)
end

# To test
# megapress_argparse(["a", "b", "c"], exc_handler=ArgParse.debug_handler)

#parsed_args = megapress_argparse(ARGS)

# rda_diff()

rda_diff("/dmf/tri_services/Facilities/Imaging/GG/180124 Megapress testing/Aimie_rda/Megapress_PCG25mmRaw1.rda",
         "/dmf/tri_services/Facilities/Imaging/GG/180124 Megapress testing/Aimie_rda/Megapress_PCG25mmRaw2.rda",
         "Aimie_rda_Megapress_PCG25mmRaw1_minus_Raw2.rda")

rda_diff("/dmf/tri_services/Facilities/Imaging/GG/180124 Megapress testing/Aimie_rda/Megapress_ThalamusRaw1.rda",
         "/dmf/tri_services/Facilities/Imaging/GG/180124 Megapress testing/Aimie_rda/Megapress_ThalamusRaw2.rda",
         "Aimie_rda_Megapress_ThalamusRaw1_minus_Raw2.rda")

rda_diff("/dmf/tri_services/Facilities/Imaging/GG/180124 Megapress testing/Alison_Volunteer/PCGMegapressRaw1.rda",
         "/dmf/tri_services/Facilities/Imaging/GG/180124 Megapress testing/Alison_Volunteer/PCGMegapressRaw2.rda",
         "Alison_Volunteer_PCGMegapressRaw1_minus_Raw2.rda")

